### ISSUE TITLE
agentsPage.svelte.test.ts: agents.list mock missing listVersions/rollback breaks 18/19 tests

### ISSUE THREAD

**Issue by jwilson411** [jwilson411/Rivulets#174]
## What's broken

`ui/src/routes/agents/agentsPage.svelte.test.ts`'s `vi.mock('$lib/api/agents', ...)` factory only stubs `list`, `create`, `update`, `remove`, `getRoutingRules`, `setRoutingRules`, `getPeerPreference`, `setPeerPreference`. It never got `listVersions`/`rollback` added when #104 (agent instructions/model version history, merged as #172) added those calls to `+page.svelte`'s `refresh()`:

```ts
const versionEntries = await Promise.all(
    agentList.map(async (a) => [a.id, await agents.listVersions(a.id)] as const)
);
```

Since the mock doesn't define `listVersions`, every test that renders the page and waits for `refresh()` to settle hits `agents.listVersions is not a function`, which `refresh()`'s catch block turns into a `loadError` — the page renders its error state instead of the agent list for the rest of the test.

## Impact

Confirmed on `main` (unmodified) via `npx vitest run src/routes/agents/agentsPage.svelte.test.ts`: **18 of 19 tests fail**, all with the same `agents.listVersions is not a function` error.

## Fix

Add `listVersions: vi.fn()` and `rollback: vi.fn()` (with appropriate return values, e.g. `vi.fn().mockResolvedValue([])`) to the `vi.mock('$lib/api/agents', ...)` factory in `agentsPage.svelte.test.ts`, matching the shape `agents.ts` actually exports.

## Notes

Found this as a side effect of working on #107 (structured, schema-constrained agent output) — unrelated to that change, confirmed present on `main` before my changes via `git stash`. Filing separately rather than folding a fix into #107's PR since it's an independent regression from #104/#172.

**Comment by jwilson411** [comment]
Closing — this was already fixed on `main` via #183 (commit 09aee72), which added the same `listVersions`/`rollback` mocks to `agentsPage.svelte.test.ts` while fixing broken CI. Confirmed on `origin/main`: the mock factory has both stubs and `beforeEach` seeds `listVersions` with `[]`. PR #177 (an independent fix for this same issue) was already closed as superseded by the author.
